apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration
  template:
    metadata:
      labels:
        app: configuration
    spec:
      containers:
        - name: configuration
          image: landrzejewski/configuration-server-tr
          ports:
            - containerPort: 8888
              name: http
          envFrom:
            - configMapRef:
                name: global-config-map

