apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-config-map
data:
  ACTIVE_PROFILE: production
  CONFIGURATION_SERVER_URI: optional:configserver:http://configuration-service:8888
  POSTGRES_DB: payments
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin