apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-database
  template:
    metadata:
      labels:
        app: payments-database
    spec:
      containers:
        - name: payments-database
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: payments-config-map
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: volume
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: payments-volume-claim

