apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app-name: configuration-server
  template:
    metadata:
      labels:
        app-name: configuration-server
    spec:
      containers:
        - name: configuration-server
          image: landrzejewski/configuration-server
          ports:
            - containerPort: 8888
              name: http
          envFrom:
            - configMapRef:
                name: configuration-server-config-map
