apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: shop-database
  template:
    metadata:
      labels:
        app-name: shop-database
    spec:
      containers:
        - name: shop-database
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
              name: shop-db
          envFrom:
            - configMapRef:
                name: shop-database-config-map
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: shop-service-volume-claim

