apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-3