apiVersion: v1
kind: Pod
metadata:
  name: updater-pod
spec:
  containers:
    - name: web-server
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: storage
    - name: updater-app
      image: landrzejewski/updater:v1
      volumeMounts:
        - mountPath: /var/htdocs/
          name: storage
  volumes:
    - name: storage
      hostPath:
        path: /tmp/updater
